# ProFiles Config File v${project.version}
# https://git.lucyy.me/Lucy/ProFiles/wiki/Setting-up-ProFiles
# Join my Discord https://support.lucyy.me for help

checkForUpdates: true

format:
  accent: "&3"
  main: "&f"

fields:
  name:
    type: "simple"
    order: 0
    displayName: "Name"
  gender:
    type: "simple"
    order: 1
    displayName: "Gender"
  pronouns:
    type: "pronouns"
    order: 2
    displayName: "Pronouns"
  discord:
    type: "simple"
    order: 3
    displayName: "Discord"