# ProFiles Config File v${project.version}
# https://git.lucyy.me/Lucy/ProFiles/wiki/Setting-up-ProFiles
# Join my Discord https://support.lucyy.me for help

checkForUpdates: true

format:
  accent: "{#fa9efa>}%s{#9dacfa<}"
  main: "&f"

subtitle:
  enabled: true

storage: yml

mysql:
  host: '127.0.0.1'
  port: 3306
  database: 'profiles'
  username: 'profiles'
  password: 'password'

fields:
  name:
    type: "simple"
    order: 0
    displayName: "Name"
  rank:
    type: "placeholder"
    order: 1
    displayName: "Rank"
    format: "%vault_prefix%"
  gender:
    type: "simple"
    order: 2
    displayName: "Gender"
  pronouns:
    type: "pronouns"
    order: 3
    displayName: "Pronouns"
  discord:
    type: "discordsrv"
    order: 4
    displayName: "Discord"