# ProFiles Config File v1.0.0-SNAPSHOT
# https://git.lucyy.me/Lucy/ProFiles/wiki/Setting-up-ProFiles
# Join my Discord https://support.lucyy.me for help

checkForUpdates: true

format:
  accent: "&3"
  main: "&f"

fields:
  name:
    type: "simple"
    displayName: "Name"
  gender:
    type: "simple"
    displayName: "Gender"
  pronouns:
    type: "pronouns"
    displayName: "Pronouns"
  discord:
    type: "simple"
    displayName: "Discord"