name: ProFiles
version: @version@
main: me.lucyy.profiles.bukkit.ProFilesBukkit
api-version: 1.16
authors: [ __lucyy ]
description: The ultimate profile plugin.
website: https://lucyy.me
softdepend: [ ProNouns, PlaceholderAPI, DiscordSRV ]
commands:
  profile:
    description: Show your profile.
    usage: /profile
    aliases: [ profiles ]

permissions:
  profiles.admin:
    description: "Access to admin commands"
    default: op
  profiles.moderator:
    description: "Access to moderation commands (setother, etc)"
    default: op