name: ProFiles
version: ${project.version}
main: me.lucyy.profiles.ProFiles
api-version: 1.16
authors: [ __lucyy ]
description: The ultimate profile plugin.
website: https://lucyy.me
softdepend: [ ProNouns, PlaceholderAPI ]
commands:
  profile:
    description: Show your profile.
    usage: /profile
    aliases: [ profiles ]

permissions:
  profiles.admin:
    description: "Access to admin commands"
    default: op