name: Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        continue-on-error: true
        with:
          java-version: 1.8

      - name: action-maven-publish
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          maven_goals_phases: "clean javadoc:javadoc package deploy"
          nexus_username: ${{ secrets.REPO_USERNAME }}
          nexus_password: ${{ secrets.REPO_PASSWORD }}
          server_id: lucy
        continue-on-error: true
      - name: Set Release version env variable
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f profiles-api/pom.xml)" >> $GITHUB_ENV

      - name: Deploy javadocs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.JAVADOC_DEPLOY_KEY }}
          external_repository: lucyy-mc/javadocs
          publish_dir: ./profiles-api/target/site/apidocs
          destination_dir: profiles/${{ env.RELEASE_VERSION }}

      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            profiles-bukkit/target/profiles-bukkit-*.jar
            profiles-api/target/profiles-api-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}